language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t davittsakadze/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true davittsakadze/docker-react npm run test